# Generated by Django 4.0.6 on 2022-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(auto_created=True, max_length=5, unique=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
